name: Capcat
main: cat.nyaa.capcat.Capcat
description: "Capitalized NyaaCraft"
version: ${version}
depend: [NyaaCore]
softdepend: [HamsterEcoHelper]
authors: [RecursiveG]
website: "https://github.com/NyaaCat/capcat"
api-version: 1.13

commands:
  capcat:
    description: The command for Capcat
    aliases: cc
    permission: cc.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  cc.command:
    description: Base permission node for commands
    default: true
  cc.tp.sign:
    description: Register a teleport sign
    default: op
  cc.tp.remove:
    description: Remove a teleport sign
    default: op
  cc.tp.create:
    description: Acquire a teleport sign
    default: true
  cc.tp.release:
    description: Release a teleport sign
    default: true
  cc.admin:
    default: op